### ISSUE TITLE
fortigate 7.4.5

### ISSUE THREAD

**Issue by Intrudr-Sec** [romainmarcoux/misc-ip-lists#1]
Bonjour Romain,

Sur mon FortiGate de lab, un 70F, j'ai le message qui indique que la limite est atteinte pour les listes de ce repertoire.

`The external resource contains more entries than is supported. The maximum amount of entries per-resource is 0. Any entries after the maximum has been reached will be dropped.`

Si tu as besoin de plus, fait moi le savoir.

merci

**Comment by romainmarcoux** [comment]
Bonjour,
C'est une nouveauté à partir de la 7.4.4, il y a un nombre maximum de 300k IP :
https://docs.fortinet.com/document/fortigate/7.4.0/new-features/677896/external-resource-entry-limit-enhancements-7-4-4

Je suis en train de négocier avec Fortinet pour qu'ils répartissent mieux ces valeurs maximum.
